import { render, screen } from "@testing-library/react";
import { describe, expect, it } from "vitest";
import LoadingSpinner from "./LoadingSpinner";

describe("LoadingSpinner", () => {
	it("renders correctly with default text", () => {
		render(<LoadingSpinner />);
		expect(screen.getByText("Cargando...")).toBeInTheDocument();
	});

	it("contains an icon with animate-spin class", () => {
		render(<LoadingSpinner />);
		// icon-Loader2 is generated by the Proxy mock in setup.tsx
		const icon = screen.getByTestId("icon-Loader2");
		expect(icon).toBeInTheDocument();
		expect(icon).toHaveClass("animate-spin");
	});
});
